AluminiConnect/static/AluminiConnect/css/creative.css
AluminiConnect/templates/AluminiConnect/index.html

Added shadows on hovering over the service-box.
Also, the link now opens on clicking anywhere on the service-box and so removed text-decoration from the anchor tags in service-box.

UI :: Enhanced service-box on homepage

---

AluminiConnect/static/AluminiConnect/css/custom.css
AluminiConnect/templates/AluminiConnect/login.html

**masthead-bg**
Wasn't displaying correctly on few devices due to excess translation in upward direction. 
Corrected by repeating the image in y-direction and then translating downwards by 400px. Not causing any problem now as the actual size of image is greater than 400px so now it's covering the whole masthead correctly.
Just have to remove style attribute from all masthead-bg divs which are creating same problem and we are good to go.
Before:
After:
**Responsive Login Page**
Working fine on all screen resolutions.
Before:
After:

UI :: Responsive Login page with some changes in masthead-bg

---

AluminiConnect/static/AluminiConnect/css/custom.css
AluminiConnect/templates/gallery/album_detail.html
AluminiConnect/templates/gallery/index.html

UI ::  Gallery Page Update

---

AluminiConnect/static/AluminiConnect/css/custom.css
AluminiConnect/templates/events_news/index.html

UI :: Responsive Events Page

---

AluminiConnect/static/AluminiConnect/css/custom.css
AluminiConnect/templates/events_news/event.html

1. Made the page responsive.
2. "+ .. More" also opens the modal of attendees now and is displayed with proper padding.

UI :: Events Details Page updated

---

AluminiConnect/templates/registration/password_reset_done.html
AluminiConnect/templates/registration/password_reset_form.html

UI :: Password Reset Page Updated

---

AluminiConnect/templates/AluminiConnect/login.html
AluminiConnect/templates/events_news/index.html
AluminiConnect/templates/gallery/album_detail.html
AluminiConnect/templates/gallery/index.html

Masthead background of Login Page, Events Page, Gallery Page and Album Details Page fixed and others will be fixed as they will be made responsive.

Fix :: masthead background fixed

---

AluminiConnect/templates/news/index.html
AluminiConnect/templates/news/news.html

UI :: News Pages Updated

---

AluminiConnect/templates/awards/award.html

UI :: Award Details Page updated

---

AluminiConnect/templates/events_news/index.html
AluminiConnect/templates/geolocation/index.html
AluminiConnect/templates/members/sacbody.html
AluminiConnect/templates/news/index.html
AluminiConnect/templates/publications/index.html
AluminiConnect/templates/publications/publication_detail.html

Fixed masthead of Publication pages, Geolocation page, Events index page, News index page and SAC body page.

Fix :: Masthead fixed

---

AluminiConnect/templates/members/sacbody.html

Profile card added in web team and web team section of page made responsive.

sacbody web team updated and made responsive

---

AluminiConnect/static/AluminiConnect/css/custom.css
AluminiConnect/templates/members/index.html

Updated Members Page.
1. Added "Filter by Graduation Year" link after search is performed as there was no way to go back to initial page after search.
2. Fixed Masthead.
3. Fixed size of profile pictures on mobile.
4. Link stretched to whole cards in Filter by Graduation Year.
5. Overall Responsiveness.

UI :: Members page updated

---

AluminiConnect/templates/members/branch.html
AluminiConnect/templates/members/year.html

UI :: Members year and branch pages updated

---

AluminiConnect/templates/alumniprofile/profile.html

1. Publications card removed from Profile page (commented out).
2. Fixed masthead.

Fix :: Removed publications from Profile page

---

AluminiConnect/static/AluminiConnect/css/custom.css
AluminiConnect/templates/AluminiConnect/index.html

All Cards in homepage will now have same height.

UI :: Fixed cards height on homepage

---

AluminiConnect/templates/gallery/index.html

Fix :: Cards width in gallery

---

AluminiConnect/static/AluminiConnect/css/custom.css
AluminiConnect/templates/members/branch.html
AluminiConnect/templates/members/index.html
AluminiConnect/templates/members/year.html

Shadow on hover effect added to all cards in members pages.

UI :: Shadow on hover effect added to members

---

AluminiConnect/AluminiConnect/urls.py
AluminiConnect/AluminiConnect/views.py
AluminiConnect/templates/AluminiConnect/index.html

Toast appears for 2 secs after login in.

Feature :: Login toast

---

AluminiConnect/templates/AluminiConnect/account_success.html
AluminiConnect/templates/AluminiConnect/alumnicard.html
AluminiConnect/templates/AluminiConnect/change_password.html
AluminiConnect/templates/AluminiConnect/confirm_email.html
AluminiConnect/templates/registration/password_reset_complete.html
AluminiConnect/templates/registration/password_reset_confirm.html

Fixed Masthead and UI of rest of the pages.

UI :: Masthead and UI fixes for rest pages

---

templates/alumniprofile/profile.html
templates/globals/base.html
templates/registration/account_verification_email_old.html

Modified social media links in profile to open in new tab and changed icons of phone. Also added social media links in footer of successful verification email

Modified icons and urls

---

AlumniConnect/decorators.py
AlumniConnect/forms.py
AlumniConnect/urls.py
AlumniConnect/views.py
applications/adminportal/views.py
applications/alumniprofile/views.py
applications/job_posting/views.py
applications/members/views.py
templates/AlumniConnect/acc_active_email.html
templates/AlumniConnect/account_activation_email.html
templates/AlumniConnect/confirm_email.html
templates/AlumniConnect/profile_completion.html
templates/AlumniConnect/profile_form.html
templates/AlumniConnect/profileedit.html

New Signup Page

---

AlumniConnect/urls.py
applications/alumniprofile/urls.py
applications/members/urls.py
applications/members/views.py
templates/members/index.html

Error occur due to alphanumeric roll number

Fix server error 500 

---

applications/adminportal/views.py

Problem -there is a limit of 500 in email 
but we can sent to many in  bcc 
so for all student I select all emails which to used and add them in a list ,name bcc
and use that list in standard mail format

Email by Admin using bcc

---

templates/members/index.html

1. This PR Add feature of the issue #151 
2. This PR modifies the index.html file of the members folder of the templates folder to display the state adjacent to city
https://github.com/BitByte-TPC/alumni/assets/163876039/46b9cde8-f609-4da5-b73d-a0f0291baa18
Thank You

Feature #151 Display state information in Profile card

---

AlumniConnect/urls.py
applications/blog/admin.py
applications/blog/forms.py
applications/blog/models.py
applications/blog/urls.py
applications/blog/views.py

1. This PR Add feature of the issue #158 
2. This PR modifies/create the following 
* Modified AlumniConnect/urls.py :  Added a new URL path /blogs.
* Created forms.py : Added necessary forms for handling data input.
* Updated models.py : Copied models.py from the feature/blog branch and Made minor modifications to adapt the existing models.
* Created/Modified urls.py : Added necessary URL patterns for the blog functionality.
* Modified views.py : Updated views to handle new and existing functionality as required.
https://github.com/BitByte-TPC/alumni/assets/163876039/b6649d7f-4065-4401-a881-ee421869d6fe
https://github.com/BitByte-TPC/alumni/assets/163876039/f29ca6a6-62cc-451e-9be6-29b0ddc7b05f
Thank You

Feature #158  Implement functionality for Blogs

---

applications/chapter/urls.py
applications/chapter/views.py
applications/news/urls.py
applications/news/views.py

Fixes #164
Description:-
This PR does the following:-
Implemented redirects to /news/ and /chapter/ if the requested news item does not exist
PROOF OF WORK:-
https://github.com/BitByte-TPC/alumni/assets/156583847/1001b758-303c-4036-999c-f8844ea97d00

Fixes #164: Redirect if data does not exist
